// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Pose.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace
{
char dummy;
}
#endif

#include "Pose.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

eprosima::geometry_msgs::msg::Pose::Pose()
{
    // m_position com.eprosima.fastrtps.idl.parser.typecode.StructTypeCode@54d9d12d

    // m_orientation com.eprosima.fastrtps.idl.parser.typecode.StructTypeCode@38425407
}

eprosima::geometry_msgs::msg::Pose::~Pose()
{
}

eprosima::geometry_msgs::msg::Pose::Pose(const Pose &x)
{
    m_position = x.m_position;
    m_orientation = x.m_orientation;
}

eprosima::geometry_msgs::msg::Pose::Pose(Pose &&x)
{
    m_position = std::move(x.m_position);
    m_orientation = std::move(x.m_orientation);
}

eprosima::geometry_msgs::msg::Pose &eprosima::geometry_msgs::msg::Pose::operator=(const Pose &x)
{

    m_position = x.m_position;
    m_orientation = x.m_orientation;

    return *this;
}

eprosima::geometry_msgs::msg::Pose &eprosima::geometry_msgs::msg::Pose::operator=(Pose &&x)
{

    m_position = std::move(x.m_position);
    m_orientation = std::move(x.m_orientation);

    return *this;
}

size_t eprosima::geometry_msgs::msg::Pose::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;

    current_alignment += eprosima::geometry_msgs::msg::Point::getMaxCdrSerializedSize(current_alignment);
    current_alignment += eprosima::geometry_msgs::msg::Quaternion::getMaxCdrSerializedSize(current_alignment);

    return current_alignment - initial_alignment;
}

size_t eprosima::geometry_msgs::msg::Pose::getCdrSerializedSize(const eprosima::geometry_msgs::msg::Pose &data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += eprosima::geometry_msgs::msg::Point::getCdrSerializedSize(data.position(), current_alignment);
    current_alignment += eprosima::geometry_msgs::msg::Quaternion::getCdrSerializedSize(data.orientation(), current_alignment);

    return current_alignment - initial_alignment;
}

void eprosima::geometry_msgs::msg::Pose::serialize(eprosima::fastcdr::Cdr &scdr) const
{

    scdr << m_position;
    scdr << m_orientation;
}

void eprosima::geometry_msgs::msg::Pose::deserialize(eprosima::fastcdr::Cdr &dcdr)
{

    dcdr >> m_position;
    dcdr >> m_orientation;
}

/*!
 * @brief This function copies the value in member position
 * @param _position New value to be copied in member position
 */
void eprosima::geometry_msgs::msg::Pose::position(const eprosima::geometry_msgs::msg::Point &_position)
{
    m_position = _position;
}

/*!
 * @brief This function moves the value in member position
 * @param _position New value to be moved in member position
 */
void eprosima::geometry_msgs::msg::Pose::position(eprosima::geometry_msgs::msg::Point &&_position)
{
    m_position = std::move(_position);
}

/*!
 * @brief This function returns a constant reference to member position
 * @return Constant reference to member position
 */
const eprosima::geometry_msgs::msg::Point &eprosima::geometry_msgs::msg::Pose::position() const
{
    return m_position;
}

/*!
 * @brief This function returns a reference to member position
 * @return Reference to member position
 */
eprosima::geometry_msgs::msg::Point &eprosima::geometry_msgs::msg::Pose::position()
{
    return m_position;
}
/*!
 * @brief This function copies the value in member orientation
 * @param _orientation New value to be copied in member orientation
 */
void eprosima::geometry_msgs::msg::Pose::orientation(const eprosima::geometry_msgs::msg::Quaternion &_orientation)
{
    m_orientation = _orientation;
}

/*!
 * @brief This function moves the value in member orientation
 * @param _orientation New value to be moved in member orientation
 */
void eprosima::geometry_msgs::msg::Pose::orientation(eprosima::geometry_msgs::msg::Quaternion &&_orientation)
{
    m_orientation = std::move(_orientation);
}

/*!
 * @brief This function returns a constant reference to member orientation
 * @return Constant reference to member orientation
 */
const eprosima::geometry_msgs::msg::Quaternion &eprosima::geometry_msgs::msg::Pose::orientation() const
{
    return m_orientation;
}

/*!
 * @brief This function returns a reference to member orientation
 * @return Reference to member orientation
 */
eprosima::geometry_msgs::msg::Quaternion &eprosima::geometry_msgs::msg::Pose::orientation()
{
    return m_orientation;
}

size_t eprosima::geometry_msgs::msg::Pose::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
    size_t current_align = current_alignment;

    return current_align;
}

bool eprosima::geometry_msgs::msg::Pose::isKeyDefined()
{
    return false;
}

void eprosima::geometry_msgs::msg::Pose::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
    (void)scdr;
}
