// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Transform.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace
{
char dummy;
}
#endif

#include "Transform.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

eprosima::geometry_msgs::msg::Transform::Transform()
{
    // m_translation com.eprosima.fastrtps.idl.parser.typecode.StructTypeCode@1165b38

    // m_rotation com.eprosima.fastrtps.idl.parser.typecode.StructTypeCode@4c12331b
}

eprosima::geometry_msgs::msg::Transform::~Transform()
{
}

eprosima::geometry_msgs::msg::Transform::Transform(const Transform &x)
{
    m_translation = x.m_translation;
    m_rotation = x.m_rotation;
}

eprosima::geometry_msgs::msg::Transform::Transform(Transform &&x)
{
    m_translation = std::move(x.m_translation);
    m_rotation = std::move(x.m_rotation);
}

eprosima::geometry_msgs::msg::Transform &eprosima::geometry_msgs::msg::Transform::operator=(const Transform &x)
{

    m_translation = x.m_translation;
    m_rotation = x.m_rotation;

    return *this;
}

eprosima::geometry_msgs::msg::Transform &eprosima::geometry_msgs::msg::Transform::operator=(Transform &&x)
{

    m_translation = std::move(x.m_translation);
    m_rotation = std::move(x.m_rotation);

    return *this;
}

size_t eprosima::geometry_msgs::msg::Transform::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;

    current_alignment += eprosima::geometry_msgs::msg::Vector3::getMaxCdrSerializedSize(current_alignment);
    current_alignment += eprosima::geometry_msgs::msg::Quaternion::getMaxCdrSerializedSize(current_alignment);

    return current_alignment - initial_alignment;
}

size_t eprosima::geometry_msgs::msg::Transform::getCdrSerializedSize(const eprosima::geometry_msgs::msg::Transform &data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    current_alignment += eprosima::geometry_msgs::msg::Vector3::getCdrSerializedSize(data.translation(), current_alignment);
    current_alignment += eprosima::geometry_msgs::msg::Quaternion::getCdrSerializedSize(data.rotation(), current_alignment);

    return current_alignment - initial_alignment;
}

void eprosima::geometry_msgs::msg::Transform::serialize(eprosima::fastcdr::Cdr &scdr) const
{

    scdr << m_translation;
    scdr << m_rotation;
}

void eprosima::geometry_msgs::msg::Transform::deserialize(eprosima::fastcdr::Cdr &dcdr)
{

    dcdr >> m_translation;
    dcdr >> m_rotation;
}

/*!
 * @brief This function copies the value in member translation
 * @param _translation New value to be copied in member translation
 */
void eprosima::geometry_msgs::msg::Transform::translation(const eprosima::geometry_msgs::msg::Vector3 &_translation)
{
    m_translation = _translation;
}

/*!
 * @brief This function moves the value in member translation
 * @param _translation New value to be moved in member translation
 */
void eprosima::geometry_msgs::msg::Transform::translation(eprosima::geometry_msgs::msg::Vector3 &&_translation)
{
    m_translation = std::move(_translation);
}

/*!
 * @brief This function returns a constant reference to member translation
 * @return Constant reference to member translation
 */
const eprosima::geometry_msgs::msg::Vector3 &eprosima::geometry_msgs::msg::Transform::translation() const
{
    return m_translation;
}

/*!
 * @brief This function returns a reference to member translation
 * @return Reference to member translation
 */
eprosima::geometry_msgs::msg::Vector3 &eprosima::geometry_msgs::msg::Transform::translation()
{
    return m_translation;
}
/*!
 * @brief This function copies the value in member rotation
 * @param _rotation New value to be copied in member rotation
 */
void eprosima::geometry_msgs::msg::Transform::rotation(const eprosima::geometry_msgs::msg::Quaternion &_rotation)
{
    m_rotation = _rotation;
}

/*!
 * @brief This function moves the value in member rotation
 * @param _rotation New value to be moved in member rotation
 */
void eprosima::geometry_msgs::msg::Transform::rotation(eprosima::geometry_msgs::msg::Quaternion &&_rotation)
{
    m_rotation = std::move(_rotation);
}

/*!
 * @brief This function returns a constant reference to member rotation
 * @return Constant reference to member rotation
 */
const eprosima::geometry_msgs::msg::Quaternion &eprosima::geometry_msgs::msg::Transform::rotation() const
{
    return m_rotation;
}

/*!
 * @brief This function returns a reference to member rotation
 * @return Reference to member rotation
 */
eprosima::geometry_msgs::msg::Quaternion &eprosima::geometry_msgs::msg::Transform::rotation()
{
    return m_rotation;
}

size_t eprosima::geometry_msgs::msg::Transform::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
    size_t current_align = current_alignment;

    return current_align;
}

bool eprosima::geometry_msgs::msg::Transform::isKeyDefined()
{
    return false;
}

void eprosima::geometry_msgs::msg::Transform::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
    (void)scdr;
}
